### PR TITLE
Theme Submission: devlopr-jekyll

### PR DESCRIPTION
**Pull request by sujaykundu777**
New theme added

### CODE REVIEW

**Comment by JugglerX** [comment]
@sujaykundu777 Thank you for the theme submission, and sorry for the delay. It's great to see a theme with so many advanced integrations (formspring, snipcart, search etc!) really nice work.

Just wanted to check something, you tagged this theme with NetlifyCMS and Contentful CMS. That means this theme should contain all of the files, schemas and configuration to work with these CMS immediately. Is that the case?

**Comment by sujaykundu777** [comment]
@JugglerX Hey :D Thanks a lot.. I am in the process of integrating it soon with NetlifyCMS and Contentful. Currently It works great with Forestry. Its under active development :D

**Comment by JugglerX** [comment]
Ok well if you can just remove any categories from the markdown file that are not finished and I can merge it. You are welcome to update it later.

Also for the theme to be listed as compatible with Forestry it must include the .forestry file with a schema, it can't just be markdown.

**Comment by sujaykundu777** [comment]
@JugglerX I have removed them for now. Anyfurther settings to be done for Forestry ? Because I see its already been listed in the CMS category. Thanks

**Pull request merged**
