### PR TITLE
Theme Submission: Clarity

### PR DESCRIPTION
**Pull request by chipzoller**

### CODE REVIEW

**Comment by JugglerX** [comment]
@chipzoller Hello, thanks for the great theme submission. Can you please ensure the demo link goes to a live demo which uses the themes demo content/first install content. Other then that, it looks good.

**Comment by chipzoller** [comment]
Hi @JugglerX I am sorry I had to use my blog despite the instructions. I did that as a temporary measure as we do not yet have a live demo site set up. Is this something you can approve and we can submit a new PR once we have that up?

**Comment by JugglerX** [comment]
We do not allow the demo URL to be the personal/business site to prevent abuse. It must be a seperate demo site with demo content.

**Comment by chipzoller** [comment]
Understand. We will set that up immediately.

**Comment by chipzoller** [comment]
Added correct demo link @JugglerX

**Pull request merged**
