### PR TITLE
Add Cereus-Pro Hugo Themes

### PR DESCRIPTION
**Pull request by arhen**

### CODE REVIEW

**Comment by JugglerX** [comment]
Does this theme work with NetlifyCMS or does it just deploy to Netlify? If it does not work with NetlifyCMS please change:

```
cms:
  - NetlifyCMS
```
to
```
cms:
  - No Cms
```

**Comment by arhen** [comment]
it using NetlifyCMS as CMS.

**Comment by arhen** [comment]
image

**Comment by JugglerX** [comment]
Awesome! It just wasnt obvious to me from the readme that it was NetlifyCMS ready. Great to see more CMS ready themes.

**Pull request merged**
