### PR TITLE
SEO & a11y improvements

### PR DESCRIPTION
**Pull request by Jinksi**
Hey stackbithq 👋

I've made some SEO and accessibility updates to the site that I'd like to contribute:
- Added alt tags to taxonomy page logos (e.g. "Gatsby Logo")
- Added alt tags and aria-label attributes to terms page links & logos (e.g. "Gatsby Logo")
- Added a meta description tag to taxonomy and terms pages, where there was none (e.g. "Gatsby Themes and Starters for JAMstack Sites.")
- Improved the filter-list a11y:
	- focus-states for keyboard navigation
	- aria attributes for screen readers

Testing locally with Chrome Lighthouse (a11y/SEO):
- Home page: was (88/89) now (100/100)
- Taxonomy page: was (82/78) now (100/100)
- Terms page: was (70/78) now (100/100)

Let me know if you have any changes or suggestions.

### CODE REVIEW

**Comment by JugglerX** [comment]
This is really great thank you!

I understand the reason behind adding the focus to the checkboxes. Is it all possible that when a mouse user uncheck's a checkbox in the filter list, that the border is not purple? Or perhaps we can change :focus to a purple glow?

**Comment by Jinksi** [comment]
Hey Robert! Good point, I missed that side-effect.

This is the perfect situation for `:focus-visible`, but browser support is not quite there yet. https://css-tricks.com/keyboard-only-focus-styles/

I've added a glow and used `:focus-visible` to remove the glow if the browser supports that pseudo-class.

focus

**Comment by JugglerX** [comment]
nice! great attention to detail, I'll merge it.

**Comment by Jinksi** [comment]
👏 cheers!

**Pull request merged**
