### PR TITLE
Theme Submission: Commercejs, Nextjs

### PR DESCRIPTION
**Pull request by jaepass**
- Submitting new theme for commercejs
- Add Nextjs taxonomy under ssg

**Thumbnail and preview image captured looks broken, requesting to submit another preview image**

### CODE REVIEW

**Comment by JugglerX** [comment]
Great submission! Thanks for adding next.js, looks like your the first person to successfully add a new ssg correctly 💯 

Would you mind making the theme name a little shorter? Perhaps "Commercejs Nextjs Starter"?

**Comment by jaepass** [comment]
Thank you for the speedy review! Definitely, on it for a shorter name! Also, was wondering if possible to submit a preview image as it looks like capture didn't quite snap a good shot

**Comment by JugglerX** [comment]
Yeah I saw the capture was off, looks like it caught it in the middle of a slide transition. 

If you want finer control over the image you can commit an image to `/static/capture/chec-commercejs-nextjs-demo-store-master.png` - it should be a 1024x768px png file. The build script does not take a screenshot if one already exists in the capture folder, it will generate the thumbnails from this file (so no need to include those)

**Comment by jaepass** [comment]
Awesome thank you 🙏 Just committed requested theme name change and preview image!

**Pull request merged**
