### PR TITLE
Theme Submission: Web-Nary

### PR DESCRIPTION
**Pull request by BRAVO68WEB**
New Hexo Theme Template Addition

### CODE REVIEW

**Review by JugglerX — COMMENTED** [review]
@BRAVO68WEB Hi, thank you for a great submission, nice to see more advanced Hexo themes!

You have tagged this as using NetlifyCMS but i'm not sure it does. I had a quick look over the repo and I don't see the NetlifyCMS supporting files or any mention of NetlifyCMS in the Readme.

Can you please confirm this uses NetlifyCMS and not just Netlify?

**Comment by JugglerX** [comment]
If it does not use NetlifyCMS then please change the theme submission cms to `No Cms`

**Comment by BRAVO68WEB** [comment]
My Bad I only uses Netlify no NetfilyCMS.

**Comment by BRAVO68WEB** [comment]
I have recommitted and fixed the changes @JugglerX

**Comment by BRAVO68WEB** [comment]
Sir Please recheck

**Pull request merged**
