### PR TITLE
Adding Sanity icon

### PR DESCRIPTION
**Pull request by hiverkiya**
#13 
Replaced sanity.png with sanity.svg and corrected its path in content/cms/sanity/_index.md
I've used some online tools to convert the existing sanity PNG to its respective SVG.
Please review the changes I've made and give your feedback on whether what I did is accurate or not.
Making only one change, for now, to ensure I'm on the right path.

### CODE REVIEW

**Comment by JugglerX** [comment]
The SVG is not correct. It is not a proper SVG. This task isn't just about converting PNGs to SVGs.

What we really need is SVG Icons that are well formed. They should have the correct paths and fill options so we can take advantage of these properties. I don't know how to create these myself but I believe it involves creating the outlines, paths etc correctly in an illustration program.

Take a look at the Gridsome icon (open it in a code editor) and compare it to the Sanity icon you have submitted. You can see the difference in the code.

**Comment by hiverkiya** [comment]
Okay sir , I'll do some research on it as I'm also new to this kind of thing. What I understand is that I've to make SVG in some kind of program ,so I'll look into that.

**Comment by hiverkiya** [comment]
@JugglerX Sir, I tried to do as much I could grasp from your valuable feedback and even if something is missing I'll be trying to fix it ASAP. Also, this PR is a part of my Hacktoberfest contribution, so I don't want it to be labeled invalid.
Let me know your review and if something lacks, I'll be putting efforts into it happily 💯

**Comment by JugglerX** [comment]
@hiverkiya there is not need to call me Sir. I appreciate your effort. But this icon is not the Sanity logo and still needs some work. 

I think this task is better for a designer who has some knowledge of SVG and is an illustrator.

I'd still like to credit you with your attempt for Hacktoberfest, how can I do that?

**Comment by hiverkiya** [comment]
Thanks a lot! I guess just closing my pull request will be enough for Hacktoberfest because it isn't mentioned to be merged. Although I did really learn about SVG and some designing stuff and felt so fantastic to find your issue open🥇 
Looking forward to any contribution I could make in the future !
And pardon me if I made any mistake. Once again, a big thanks for your wonderful support and feedback! :) 💯

**Pull request closed without merging**
